# pre-commit run --all-files
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.0.1
      hooks:
      -   id: check-ast
      -   id: check-builtin-literals
      -   id: check-case-conflict
      -   id: check-docstring-first
      -   id: check-json
      -   id: check-yaml
      -   id: detect-private-key
      -   id: end-of-file-fixer
      -   id: forbid-new-submodules
      -   id: trailing-whitespace
      -   id: mixed-line-ending
      -   id: requirements-txt-fixer
      -   id: no-commit-to-branch
          args: [ -b master ]
    - repo: https://gitlab.com/pycqa/flake8
      rev: 3.9.2
      hooks:
      -   id: flake8
          args: [ '--count' ]
    - repo: https://github.com/pre-commit/mirrors-isort
      rev: v5.9.3
      hooks:
      -   id: isort
          args: ["--profile", "black"]
    - repo: https://github.com/Lucas-C/pre-commit-hooks-safety
      rev: v1.2.2
      hooks:
          - id: python-safety-dependencies-check
    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: v0.910-1
      hooks:
      -   id: mypy
          args: [--ignore-missing-imports]
          exclude: "intent/app/api/routes/v1/endpoints/slot_type.py"
          additional_dependencies:
          - 'pydantic'
    - repo: https://github.com/ambv/black
      rev: 21.9b0
      hooks:
      -   id: black
          language_version: python3
