version: '3.3'

services:
    minio:
        image: minio/minio
        container_name: minio
        ports:
            - "9001:9001"
        environment:
            - MINIO_ROOT_USER=minioadmin
            - MINIO_ROOT_PASSWORD=minioadmin
        command: minio server minio_data --console-address ":9001"

    mlflow:
        build:
            context: .
            dockerfile: Dockerfile.mlflow
        container_name: mlflow
        ports:
            - "5000:5000"
        environment:
            - AWS_ACCESS_KEY_ID=minioadmin
            - AWS_SECRET_ACCESS_KEY=minioadmin
            - MLFLOW_S3_ENDPOINT_URL=http://minio:9000
        command: 'mlflow server --backend-store-uri sqlite:///mlflow.db --default-artifact-root s3://mlflow --host 0.0.0.0'
        depends_on:
            - minio
    
    workflow:
        build:
            context: .
            dockerfile: Dockerfile.workflow
        container_name: workflow
        ports:
            - "3000:3000"
        command: dagit -f mlops/pipeline.py --host 0.0.0.0
        depends_on:
            - mlflow
            - minio
